### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by mylastore** [loicnestler/instagram-basic-display#1]
I am getting this error after running your example.
```
 data: {
      error_type: 'OAuthException',
      code: 400,
      error_message: 'Invalid authorization code'
    }
  },
  isAxiosError: true,
  toJSON: [Function (anonymous)],
  expose: true,
  statusCode: 422,
  status: 422,
  name: 'Error',
  message: 'Request failed with status code 400',
  stack: 'Error: Request failed with status code 400\n' +
    '    at createError (/Volumes/BK/seoblog/api/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at settle (/Volumes/BK/seoblog/api/node_modules/axios/lib/core/settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/Volumes/BK/seoblog/api/node_modules/axios/lib/adapters/http.js:236:11)\n' +
    '    at IncomingMessage.emit (events.js:326:22)\n' +
    '    at endReadableNT (_stream_readable.js:1244:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
```

**Comment by loicnestler** [comment]
Did you follow the "Getting started" tutorial for the basic display API?

https://developers.facebook.com/docs/instagram-basic-display-api/getting-started
